list = ["apple", "banana", "grape", "orange", "grape"]
print(list)
print(list[2])
list.append("watermelon")
list.insert(1,"grapefruit")
print(list)
list.remove("grape")
print(list)
print(range(len(list)))
help(list)
